// Generated by Wrangler on Sat May 25 2024 03:35:06 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	SHOPIFY_SESSIONS: KVNamespace;
	SHOPIFY_APP_URL: string;
	SHOPIFY_API_KEY: string;
	SHOPIFY_API_SECRET: string;
	SCOPES: string;
}
