name: Run Linting, Formatting, Type Checking, and Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  checksAndTests:
    name: Run Checks and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      # - name: Run Lint Checks
      #   run: npm run lint:check

      # - name: Run Format Checks
      #   run: npm run format:check

      - name: Run Typescript Checks
        run: npm run typecheck

      - name: Run Unit Tests
        run: npm run test

      # - name: "Run Test Coverage"
        # run: npm run test:coverage
